// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvnormFA_rowwiseCpp
arma::vec dmvnormFA_rowwiseCpp(const arma::mat& Xmat, const arma::vec& mu, const arma::mat& Lambda, const arma::vec& Psi_diag);
RcppExport SEXP _synergyMixR_dmvnormFA_rowwiseCpp(SEXP XmatSEXP, SEXP muSEXP, SEXP LambdaSEXP, SEXP Psi_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Psi_diag(Psi_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnormFA_rowwiseCpp(Xmat, mu, Lambda, Psi_diag));
    return rcpp_result_gen;
END_RCPP
}
// faEMupdateCpp
Rcpp::List faEMupdateCpp(const arma::mat& Xmat, int r, int nIterFA);
RcppExport SEXP _synergyMixR_faEMupdateCpp(SEXP XmatSEXP, SEXP rSEXP, SEXP nIterFASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nIterFA(nIterFASEXP);
    rcpp_result_gen = Rcpp::wrap(faEMupdateCpp(Xmat, r, nIterFA));
    return rcpp_result_gen;
END_RCPP
}
// faEMupdateWeightedCpp
Rcpp::List faEMupdateWeightedCpp(const arma::mat& Xmat, int r, int nIterFA, const arma::vec& weights);
RcppExport SEXP _synergyMixR_faEMupdateWeightedCpp(SEXP XmatSEXP, SEXP rSEXP, SEXP nIterFASEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nIterFA(nIterFASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(faEMupdateWeightedCpp(Xmat, r, nIterFA, weights));
    return rcpp_result_gen;
END_RCPP
}
// mfaTimeseriesSoftCpp
Rcpp::List mfaTimeseriesSoftCpp(Rcpp::List list_of_data, int K, int r, int max_iter, int nIterFA, double tol, IntegerVector z_init, bool verbose, int n_threads, int seed);
RcppExport SEXP _synergyMixR_mfaTimeseriesSoftCpp(SEXP list_of_dataSEXP, SEXP KSEXP, SEXP rSEXP, SEXP max_iterSEXP, SEXP nIterFASEXP, SEXP tolSEXP, SEXP z_initSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type list_of_data(list_of_dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nIterFA(nIterFASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mfaTimeseriesSoftCpp(list_of_data, K, r, max_iter, nIterFA, tol, z_init, verbose, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
// mfaTimeseriesCpp
Rcpp::List mfaTimeseriesCpp(Rcpp::List list_of_data, int K, int r, int max_iter, int nIterFA, double tol, Rcpp::Nullable<Rcpp::IntegerVector> z_init, bool verbose, int n_threads, int seed, Rcpp::Nullable<Rcpp::Function> progress_callback);
RcppExport SEXP _synergyMixR_mfaTimeseriesCpp(SEXP list_of_dataSEXP, SEXP KSEXP, SEXP rSEXP, SEXP max_iterSEXP, SEXP nIterFASEXP, SEXP tolSEXP, SEXP z_initSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP progress_callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type list_of_data(list_of_dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nIterFA(nIterFASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type progress_callback(progress_callbackSEXP);
    rcpp_result_gen = Rcpp::wrap(mfaTimeseriesCpp(list_of_data, K, r, max_iter, nIterFA, tol, z_init, verbose, n_threads, seed, progress_callback));
    return rcpp_result_gen;
END_RCPP
}
// dmvnormPCA_rowwiseCpp
arma::vec dmvnormPCA_rowwiseCpp(const arma::mat& Xmat, const arma::vec& mu, const arma::mat& W, double sigma2);
RcppExport SEXP _synergyMixR_dmvnormPCA_rowwiseCpp(SEXP XmatSEXP, SEXP muSEXP, SEXP WSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnormPCA_rowwiseCpp(Xmat, mu, W, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// pcaEMupdateCpp
Rcpp::List pcaEMupdateCpp(const arma::mat& Xmat, int r, int nIter);
RcppExport SEXP _synergyMixR_pcaEMupdateCpp(SEXP XmatSEXP, SEXP rSEXP, SEXP nIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    rcpp_result_gen = Rcpp::wrap(pcaEMupdateCpp(Xmat, r, nIter));
    return rcpp_result_gen;
END_RCPP
}
// pcaClosedFormCpp
Rcpp::List pcaClosedFormCpp(const arma::mat& Xmat, int r);
RcppExport SEXP _synergyMixR_pcaClosedFormCpp(SEXP XmatSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(pcaClosedFormCpp(Xmat, r));
    return rcpp_result_gen;
END_RCPP
}
// pcaEMupdateWeightedCpp
Rcpp::List pcaEMupdateWeightedCpp(const arma::mat& Xmat, int r, int nIter, const arma::vec& weights);
RcppExport SEXP _synergyMixR_pcaEMupdateWeightedCpp(SEXP XmatSEXP, SEXP rSEXP, SEXP nIterSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(pcaEMupdateWeightedCpp(Xmat, r, nIter, weights));
    return rcpp_result_gen;
END_RCPP
}
// mpcaTimeseriesSoftCpp
Rcpp::List mpcaTimeseriesSoftCpp(Rcpp::List list_of_data, int K, int r, int max_iter, int nIterPCA, double tol, std::string method, IntegerVector z_init, bool verbose, int n_threads, int seed);
RcppExport SEXP _synergyMixR_mpcaTimeseriesSoftCpp(SEXP list_of_dataSEXP, SEXP KSEXP, SEXP rSEXP, SEXP max_iterSEXP, SEXP nIterPCASEXP, SEXP tolSEXP, SEXP methodSEXP, SEXP z_initSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type list_of_data(list_of_dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nIterPCA(nIterPCASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mpcaTimeseriesSoftCpp(list_of_data, K, r, max_iter, nIterPCA, tol, method, z_init, verbose, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
// mpcaTimeseriesCpp
Rcpp::List mpcaTimeseriesCpp(Rcpp::List list_of_data, int K, int r, int max_iter, int nIterPCA, double tol, std::string method, Rcpp::Nullable<Rcpp::IntegerVector> z_init, bool verbose, int n_threads, int seed, Rcpp::Nullable<Rcpp::Function> progress_callback);
RcppExport SEXP _synergyMixR_mpcaTimeseriesCpp(SEXP list_of_dataSEXP, SEXP KSEXP, SEXP rSEXP, SEXP max_iterSEXP, SEXP nIterPCASEXP, SEXP tolSEXP, SEXP methodSEXP, SEXP z_initSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP progress_callbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type list_of_data(list_of_dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nIterPCA(nIterPCASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type progress_callback(progress_callbackSEXP);
    rcpp_result_gen = Rcpp::wrap(mpcaTimeseriesCpp(list_of_data, K, r, max_iter, nIterPCA, tol, method, z_init, verbose, n_threads, seed, progress_callback));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_synergyMixR_dmvnormFA_rowwiseCpp", (DL_FUNC) &_synergyMixR_dmvnormFA_rowwiseCpp, 4},
    {"_synergyMixR_faEMupdateCpp", (DL_FUNC) &_synergyMixR_faEMupdateCpp, 3},
    {"_synergyMixR_faEMupdateWeightedCpp", (DL_FUNC) &_synergyMixR_faEMupdateWeightedCpp, 4},
    {"_synergyMixR_mfaTimeseriesSoftCpp", (DL_FUNC) &_synergyMixR_mfaTimeseriesSoftCpp, 10},
    {"_synergyMixR_mfaTimeseriesCpp", (DL_FUNC) &_synergyMixR_mfaTimeseriesCpp, 11},
    {"_synergyMixR_dmvnormPCA_rowwiseCpp", (DL_FUNC) &_synergyMixR_dmvnormPCA_rowwiseCpp, 4},
    {"_synergyMixR_pcaEMupdateCpp", (DL_FUNC) &_synergyMixR_pcaEMupdateCpp, 3},
    {"_synergyMixR_pcaClosedFormCpp", (DL_FUNC) &_synergyMixR_pcaClosedFormCpp, 2},
    {"_synergyMixR_pcaEMupdateWeightedCpp", (DL_FUNC) &_synergyMixR_pcaEMupdateWeightedCpp, 4},
    {"_synergyMixR_mpcaTimeseriesSoftCpp", (DL_FUNC) &_synergyMixR_mpcaTimeseriesSoftCpp, 11},
    {"_synergyMixR_mpcaTimeseriesCpp", (DL_FUNC) &_synergyMixR_mpcaTimeseriesCpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_synergyMixR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
