# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnormFA_rowwiseCpp <- function(Xmat, mu, Lambda, Psi_diag) {
    .Call(`_synergyMixR_dmvnormFA_rowwiseCpp`, Xmat, mu, Lambda, Psi_diag)
}

faEMupdateCpp <- function(Xmat, r, nIterFA) {
    .Call(`_synergyMixR_faEMupdateCpp`, Xmat, r, nIterFA)
}

faEMupdateWeightedCpp <- function(Xmat, r, nIterFA, weights) {
    .Call(`_synergyMixR_faEMupdateWeightedCpp`, Xmat, r, nIterFA, weights)
}

mfaTimeseriesSoftCpp <- function(list_of_data, K, r, max_iter, nIterFA, tol, z_init, verbose, n_threads, seed) {
    .Call(`_synergyMixR_mfaTimeseriesSoftCpp`, list_of_data, K, r, max_iter, nIterFA, tol, z_init, verbose, n_threads, seed)
}

mfaTimeseriesCpp <- function(list_of_data, K, r, max_iter, nIterFA, tol, z_init = NULL, verbose = TRUE, n_threads = 0L, seed = 0L, progress_callback = NULL) {
    .Call(`_synergyMixR_mfaTimeseriesCpp`, list_of_data, K, r, max_iter, nIterFA, tol, z_init, verbose, n_threads, seed, progress_callback)
}

dmvnormPCA_rowwiseCpp <- function(Xmat, mu, W, sigma2) {
    .Call(`_synergyMixR_dmvnormPCA_rowwiseCpp`, Xmat, mu, W, sigma2)
}

pcaEMupdateCpp <- function(Xmat, r, nIter) {
    .Call(`_synergyMixR_pcaEMupdateCpp`, Xmat, r, nIter)
}

pcaClosedFormCpp <- function(Xmat, r) {
    .Call(`_synergyMixR_pcaClosedFormCpp`, Xmat, r)
}

pcaEMupdateWeightedCpp <- function(Xmat, r, nIter, weights) {
    .Call(`_synergyMixR_pcaEMupdateWeightedCpp`, Xmat, r, nIter, weights)
}

mpcaTimeseriesSoftCpp <- function(list_of_data, K, r, max_iter, nIterPCA, tol, method, z_init, verbose, n_threads, seed) {
    .Call(`_synergyMixR_mpcaTimeseriesSoftCpp`, list_of_data, K, r, max_iter, nIterPCA, tol, method, z_init, verbose, n_threads, seed)
}

mpcaTimeseriesCpp <- function(list_of_data, K, r, max_iter, nIterPCA, tol, method = "EM", z_init = NULL, verbose = TRUE, n_threads = 0L, seed = 0L, progress_callback = NULL) {
    .Call(`_synergyMixR_mpcaTimeseriesCpp`, list_of_data, K, r, max_iter, nIterPCA, tol, method, z_init, verbose, n_threads, seed, progress_callback)
}

